include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_single_quotes
    - require_trailing_commas

dart_code_metrics:
  rules:
    - prefer-trailing-comma

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    todo: ignore
